backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - label: "???ㅼ젙"
    name: "home"
    files:
      - label: "??諛곕꼫/臾멸뎄)"
        name: "home_index"
        file: "content/_index.md"
        fields:
          - { label: "?쒕ぉ", name: "title", widget: "string", default: "??媛援? }
          - { label: "諛곕꼫 ?대?吏", name: "heroImage", widget: "image" }

  - name: "products"
    label: "?곹뭹"
    folder: "content/products"
    create: true
    format: "yaml"
    extension: "yaml"
    slug: "{{slug}}"
    fields:
      - { label: "移댄뀒怨좊━", name: "category", widget: "select", options: ["梨낆긽","?섏옄","?뚰떚??,"罹먮퉬??,"?뚯쓽?뚯씠釉?,"?쒕엻","梨낆옣","湲고?"], default: "湲고?" }
      - { label: "?먮ℓ?꾨즺", name: "soldOut", widget: "boolean", default: false, required: false }

      - { label: "?곹뭹紐?, name: "title", widget: "string" }
      - { label: "媛寃?, name: "price", widget: "number" }
      - { label: "釉뚮옖??, name: "brand", widget: "string", required: false }
      - { label: "?곹깭", name: "condition", widget: "select", options: ["??,"以?,"??] }
      - { label: "?대?吏", name: "images", widget: "list", field: { label: "?대?吏", name: "image", widget: "image" } }
      - { label: "?곸꽭 ?ㅻ챸", name: "body", widget: "markdown" }
